Resources:
    GatewayResponseDefault4XX:
        Type: 'AWS::ApiGateway::GatewayResponse'
        Properties:
            ResponseParameters:
                gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
                gatewayresponse.header.Access-COntrol-Allow-Header: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
            Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
        Type: 'AWS::ApiGateway::GatewayResponse'
        Properties:
            ResponseParameters:
                gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
                gatewayresponse.header.Access-Control-Allow-Header: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
            Ref: 'ApiGatewayRestApi'